// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gsea_score_C
double gsea_score_C(NumericVector hit_scores, NumericVector inds, int num_genes);
RcppExport SEXP _csea_gsea_score_C(SEXP hit_scoresSEXP, SEXP indsSEXP, SEXP num_genesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type hit_scores(hit_scoresSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type inds(indsSEXP);
    Rcpp::traits::input_parameter< int >::type num_genes(num_genesSEXP);
    rcpp_result_gen = Rcpp::wrap(gsea_score_C(hit_scores, inds, num_genes));
    return rcpp_result_gen;
END_RCPP
}
// rdirichlet_cpp
NumericMatrix rdirichlet_cpp(NumericMatrix alpha);
RcppExport SEXP _csea_rdirichlet_cpp(SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rdirichlet_cpp(alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_csea_gsea_score_C", (DL_FUNC) &_csea_gsea_score_C, 3},
    {"_csea_rdirichlet_cpp", (DL_FUNC) &_csea_rdirichlet_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_csea(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
