# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gsea_score_C <- function(hit_scores, inds, num_genes) {
    .Call(`_csea_gsea_score_C`, hit_scores, inds, num_genes)
}

rdirichlet_cpp <- function(alpha) {
    .Call(`_csea_rdirichlet_cpp`, alpha)
}

